services:
  autodash_database:
    image: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"

  autodash_api:
    image: autodash-api
    entrypoint: ["/app/entrypoint.sh"]
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - autodash_database
    environment:
      DATABASE_URL: ${DATABASE_URL}
      GH_CALLBACK_URL: ${GH_CALLBACK_URL}
      GH_CLIENT_SECRET: ${GH_CLIENT_SECRET}
      GH_CLIENT_ID: ${GH_CLIENT_ID}
      CLAUDE_API_KEY: ${CLAUDE_API_KEY}
      OPENAI_API_KEY: ${OPENAI_API_KEY}

volumes:
  pgdata: